# Host inventory for ansible-managed hosts.
# Make sure the ansible_user and ssh key exists on each host.
#
# For more context, see: 
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
#
all:
  hosts:  # individual hosts
    
    # proxmox
    proxmox:
      ansible_host: 192.168.20.10

    # PVE
    #pve:
    #  ansible_host: 192.168.20.15

    # GCP      
    sandbox:
      ansible_host: sandbox.brooks.haus

    # Yoshi
    yoshi:
      ansible_host: 192.168.69.105

    # lxc-test
    lxc-test:
      ansible_host: 192.168.69.108
  
  children: # groups of hosts
    
    # prod hosts
    srv:
      hosts:
        chunky:
          ansible_host: 192.168.20.200
        homebot:
          ansible_host: 192.168.20.201
    
    # pihole
    pihole:
      hosts:
        pihole-a:
          ansible_host: 192.168.69.10
        pihole-b:
          ansible_host: 192.168.69.11

    # vectra hosts
    vectra:
      hosts:
        kali-se:
          ansible_host: 10.254.20.120
        kali-partner:
          ansible_host: 10.250.20.118
