# Host inventory for ansible-managed hosts.
# Make sure the ansible_user and ssh key exists on each host.
#
# For more context, see: 
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
#
all:
  hosts:  # individual hosts

    servo:
      ansible_host: 10.9.1.200

    tailscale:
      ansible_host: 10.9.1.222

    proxmox:
      ansible_host: 10.9.1.10

    homebot:
      ansible_host: 10.9.1.201