# Host inventory for ansible-managed hosts.
# Make sure the ansible_user and ssh key exists on each host.
#
# For more context, see: 
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
#
all:
  hosts:  # individual hosts

    # servo
    servo:
      ansible_host: 192.168.20.10

    # tinyprox
    tinyprox:
      ansible_host: 192.168.20.11

    # proxmox
    proxmox:
      ansible_host: 192.168.20.10

    # homebot
    homebot:
      ansible_host: 192.168.20.201

  children: # groups of hosts
    
    # piholes
    piholes:
      hosts:
        pihole-a:
          ansible_host: 192.168.20.15
