# Galaxy
collections:
  - name: community.general

roles:
  - name: bertvv.samba
  - name: geerlingguy.docker
  - name: geerlingguy.github-users
  - name: geerlingguy.nfs
  - name: geerlingguy.security
  - name: grog.package
  - name: simoncaron.pve_addons
