# Requirements from Ansible Galaxy
# https://galaxy.ansible.com
#

collections:
  - name: community.general
  - name: vladgh.samba

roles:
  - name: buluma.mount
  - name: geerlingguy.docker
  - name: geerlingguy.dotfiles
  - name: geerlingguy.github-users
  - name: geerlingguy.nfs
  - name: geerlingguy.ntp
  - name: grog.package
  - name: simoncaron.pve_addons
