---
## Random plays for testing.

  - hosts: servo
    vars_files:
      - 'vars/common.yaml'
    become: yes

    tasks:
     #Sanoid configuration for automated ZFS snapshots
      - name: Create /etc/sanoid directory
        ansible.builtin.file:
          path: /etc/sanoid
          state: directory
          mode: 0755

      - name: Copy sanoid configuration template
        ansible.builtin.template:
          src: servo/sanoid/sanoid.conf.j2
          dest: /etc/sanoid/sanoid.conf
          owner: root
          group: root
          mode: 0644

      - name: Install syncoid cron
        ansible.builtin.template:
          src: servo/sanoid/syncoid-cron.j2
          dest: /etc/cron.d/syncoid
          owner: root
          group: root
          mode: 0644

      - name: Restart cron
        command: service cron restart

      #- name: Install syncoid systemd service
      #  ansible.builtin.template:
      #    src: servo/sanoid/syncoid.service.j2
      #    dest: /etc/systemd/system/syncoid.service
      #    owner: root
      #    group: root
      #    mode: 0755
      #    lstrip_blocks: yes

      #- name: Install syncoid systemd timer
      #  ansible.builtin.template:
      #    src: servo/sanoid/syncoid.timer.j2
      #    dest: /etc/systemd/system/syncoid.timer
      #    owner: root
      #    group: root
      #    mode: 0755
      #    lstrip_blocks: yes

      - name: Enable syncoid systemd service
        ansible.builtin.systemd:
          name: syncoid
          enabled: no
          state: stopped
          masked: no

      - name: Enable syncoid systemd timer
        ansible.builtin.systemd:
          name: syncoid.timer
          enabled: no
          state: stopped
    
    #roles:
    #  - role: geerlingguy.nfs
