---
## Random plays for testing.

  - hosts: servo
    vars_files:
      - 'vars/common.yaml'
    become: yes

    tasks:
      # Add Backup disk to /etc/fstab
      - name: Copy sanoid configuration template
        ansible.builtin.template:
          src: servo/sanoid/sanoid.conf.j2
          dest: /etc/sanoid/sanoid.conf
          owner: root
          group: root
          mode: 0644
    
    #roles:
    #  - role: geerlingguy.nfs
