---
## Random plays for testing.

  - hosts: proxmox
    vars_files:
      - 'vars/common.yaml'
    become: yes

    tasks:
      # Copies shell script which eases cloud-init template creation    
      - name: Copy cloud-init template deployment script
        ansible.builtin.template:
          src: roles/dab-proxmox/templates/deploy-cloud-init-template.sh.j2
          dest: "/root/deploy-cloud-init-template.sh"
          mode: 0744

    #roles:
    #  - dab-proxmox
      
