---
## Handles updating access and packages on defined hosts.

  - hosts: all
    become: yes
    tasks:
      - name: import keys from github
        ansible.posix.authorized_key:
          user: "{{ ansible_user }}"
          state: present
          key: https://github.com/economycomfort.keys

      - name: update packages
        ansible.builtin.package:
          name: '*'
          state: latest

  - hosts: srv:pihole:proxmox:tinyprox
    become: yes      
    roles:
      - role: dab-motd

  - hosts: proxmox
    tasks:
    roles:
      - role: simoncaron.pve_addons

  - hosts: pihole
    tasks:
    - name: update pihole
      command: 'pihole -up'
