---
## Handles updating access and packages on defined hosts.

  - hosts: proxmox
    tasks:
    roles:
      - role: simoncaron.pve_addons

  - hosts: srv:proxmox
    tasks:
     - name: import keys from github
       become: yes
       ansible.posix.authorized_key:
         user: "{{ ansible_user }}"
         state: present
         key: https://github.com/economycomfort.keys

     - name: update packages
       become: yes
       ansible.builtin.package:
         name: '*'
         state: latest
