---
proxmox_become: false
proxmox_clustering: false  # Disabling can be useful for single node
proxmox_scripts_dir: /root/scripts  # where proxmox scripts go
proxmox_timezone: UTC
proxmox_lxc_template_storage: local
proxmox_lxc_templates:
  - name: debian-13-standard
    section: system
    match: '^debian-13-standard_.*_amd64\.tar\.(zst|xz|gz)$'
proxmox_iso_dir: /var/lib/vz/template/iso
proxmox_iso_images:
  - name: kali-linux-installer-amd64
    filename: kali-linux-2026.1-installer-amd64.iso
    url: https://cdimage.kali.org/current/kali-linux-2026.1-installer-amd64.iso
    checksum: sha256:271477ad6ea2676c7346576971b9acc2d32fabd9c2bbaf0e6302397626149306
proxmox_iommu_kernel_args:
  - intel_iommu=on
  - iommu=pt
proxmox_backup_file_prefix: pve-etc  # filename prefix of backup files
proxmox_backup_retention_days: 90  # number of daily backups to retain
proxmox_backup_systemd_service: pve-config-backup
proxmox_backup_systemd_timer: pve-config-backup.timer
proxmox_backup_dests:  # where pve /etc backups go
  - /mnt/pve/ext-ssd/pve-etc
proxmox_backup_list:  # Files/directories to include in backup.
  - /etc/aliases 
  - /etc/cron* 
  - /etc/default/grub
  - /etc/hostname
  - /etc/hosts 
  - /etc/kernel/cmdline
  - /etc/ksmtuned.conf
  - /etc/lvm/ 
  - /etc/modprobe.d/
  - /etc/network/interfaces 
  - /etc/pve/ 
  - /etc/resolv.conf 
  - /etc/sysctl.conf
  - /etc/vzdump.conf 
  - /etc/zfs/
