---
## Remove unnecessary login messages.

- name: Remove Ubuntu MOTD spam
  ansible.builtin.file:
    path: "/etc/update-motd.d/{{ item }}"
    state: absent
  loop:
    - 80-livepatch
    - 88-esm-announce
    - 91-contract-ua-esm-status
    - 95-hwe-eol
    - 10-help-text
    - 50-motd-news
  when: ansible_distribution == "Ubuntu"

- name: Remove Debian MOTD legalese
  ansible.builtin.file:
    path: "/etc/motd"
    state: absent
  when: (ansible_distribution == "Debian") or 
        (ansible_distribution == "Kali")
