---
## Manages creating and mounting filesystems.
## DEPRECATED: using buluma.mount instead - very similar but more flexibility.

# This is ugly, but avoids a lot of conditionals later.
# Idea is that all these lists may not be defined, so this flattens the existing lists
# into one big list-of-dicts (mountpoints).
- name: Reticulating splines
  set_fact:
    mountpoints: 
      "{{ bind_mounts | default([]) \
      + nfs_mounts | default([]) }}" 
  tags:
    - mountpoints

- name: Create mountpoints
  file:
    dest: "{{ item.mountpoint }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777
  loop: "{{ mountpoints }}"
  when: item.mountpoint is defined
  tags:
    - mountpoints

- name: Mount NFS shares
  mount:
    name: "{{ item.mountpoint }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype | default('nfs4') }}"
    opts: "{{ item.opts | default('rw,sync,hard,intr') }}"
    # change to 'present' to skip auto-mount
    state: "{{ item.state | default('mounted') }}"
  loop: "{{ nfs_mounts }}"
  when: nfs_mounts is defined
  tags:
    - nfs
    - mountpoints

- name: Create bind mounts for NFS exports
  mount:
    name: "{{ item.mountpoint }}"
    src: "{{ item.src }}"
    fstype: none
    opts: "{{ item.opts | default('bind') }}"
    # change to 'present' to skip auto-mount
    state: "{{ item.state | default('mounted') }}"
  loop: "{{ bind_mounts }}"
  when: bind_mounts is defined
  tags:
    - bindfs
    - mountpoints

- name: Check to see if ZFS is installed
  package_facts:
    manager: "auto"
  tags:
    - zfs

- name: Install docker override to wait for ZFS
  template:
    src: zfs-override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  when: 
    - ansible_distribution == "Ubuntu"
    - "'zfsutils-linux' in ansible_facts.packages"
  tags:
    - docker
    - zfs
