---
# Handles various individual tasks.

#- name: restart storage networking
#  service:
#    name: networking
#    state: restarted

#- name: restart storage networking
#  ansible.builtin.command: 
#    cmd: "bash -c 'ip a flush {{ storage_interface }} && ifdown {{ storage_interface }} && ifup {{ storage_interface }}'"
#  when: ansible_distribution == 'Debian'

- name: restart storage networking (Debian-based)
  ansible.builtin.shell:
    cmd: |
      ip a flush {{ storage_interface }}
      ip link set {{ storage_interface }} down
      ip link set {{ storage_interface }} up
  when: ansible_os_family == 'Debian'
