---
## Handles individual event-driven tasks.

- name: Restart networking (Debian)
  ansible.builtin.shell:
    cmd: |
      ip a flush {{ item.name }}
      ifdown {{ item.name }}
      ifup {{ item.name }}
  loop: "{{ network_interfaces }}"
  when: ansible_distribution == 'Debian'

- name: Restart networking (Ubuntu)
  ansible.builtin.shell:
    cmd: netplan apply
  when: ansible_distribution == 'Ubuntu'
