---
target_os: ubuntu
ansible_become: yes
ansible_user: david
ansible_python_interpreter: /usr/bin/python3

########################
###  dab-networking  ###
########################
network_interfaces:
  - name: ens18
    dhcp: true
    #ip: '192.168.20.200/24'
    #gateway: '192.168.20.1'
    #dns: '192.168.20.1'
    #domain: brooks.haus
    #mtu: 1500
  - name: ens19
    ip: '10.255.255.200/24'
    mtu: 9000

#############
###  ZFS  ###
#############
# NOTE: The pool(s) below should be created and imported.
# Frankly, not worth writing a whole role to do this, since any data on them
# shouldn't go away -- if we're reprovisioning a whole ZFS pool from scratch,
# something else has happened.
zfs_pools:
  - name: tank
    mountpoint: /mnt/tank

######################
###  buluma.mount  ###
######################
# We're only creating bind mounts on this host, not mounting remote filesystems.
mount_requests:
  - path: /srv/nfs/vm-backups
    src: /mnt/tank/backups/vm
    opts: "bind,defaults,nofail,x-systemd.requires=zfs-mount.service"
    fstype: none
  - path: /srv/nfs/media
    src: /mnt/tank/media
    opts: "bind,defaults,nofail,x-systemd.requires=zfs-mount.service"
    fstype: none
  - path: /srv/nfs/appdata
    src: /mnt/tank/appdata
    opts: "bind,defaults,nofail,x-systemd.requires=zfs-mount.service"
    fstype: none

############################
###  geerlingguy.docker  ###
############################
docker_edition: "ce"
docker_packages_state: latest
docker_install_compose_plugin: true
docker_compose_package: docker-compose-plugin
docker_compose_package_state: latest
docker_users: 
  - david

#########################
###  geerlingguy.nfs  ###
#########################
nfs_exports:
  #-"/srv/nfs               10.255.255.0/24(rw,sync,no_subtree_check,crossmnt)"
  - "/srv/nfs/appdata       10.255.255.0/24(rw,sync,no_subtree_check)"
  - "/srv/nfs/media         10.255.255.0/24(rw,sync,no_subtree_check)"
  - "/srv/nfs/vm-backups    10.255.255.10/32(rw,sync,no_subtree_check,no_root_squash)"

######################
###  grog.package  ###
###################### 
package_list:
  - name: avahi-daemon
  - name: fio
  - name: iftop
  - name: iotop
  - name: mc
  - name: ncdu
  - name: net-tools
  - name: nfs-kernel-server
  - name: nmap
  - name: qemu-guest-agent
  - name: samba
  - name: sanoid
  - name: smartmontools
  - name: ssh-import-id
  - name: tmux
  - name: tree
  - name: zfsutils-linux
  - name: zsh

#############################
###  vladgh.samba.server  ###
#############################
# Make sure the smb.conf template handles {{ ansible_managed }} appropriately at the top.
samba_apple_extensions: yes
samba_guest_account: nobody
samba_load_homes: true  # shares user $HOME automatically
samba_log: /var/log/samba.log
samba_log_level: 1
#samba_mitigate_cve_2017_7494: false  # unneeded for samba >4.6.4
samba_global_include: samba-global.conf  # in master templates dir
samba_shares:
  - name: media
    comment: A place for pirates.
    path: /mnt/tank/media
    public: false
    guest_ok: false
    writable: true
  - name: timemachine
    comment: MacOS backups.
    # This may make a literal "%U" directory to serve, vs. extrapolating to the Samba user.
    # Manually correcting the file and restarting the process can fix.  Not sure why.
    path: "/mnt/tank/backups/timemachine/%U"
    include_file: samba-timemachine.conf  # in master templates dir

