---
target_os: ubuntu
ansible_become: yes
ansible_user: david
ansible_python_interpreter: /usr/bin/python3


########################
###  dab-networking  ###
########################
network_interfaces:
  - name: ens18
    dhcp: true
    #ip: '192.168.20.200/24'
    #gateway: '192.168.20.1'
    #dns: '192.168.20.1'
    #domain: brooks.haus
    #mtu: 1500
  - name: ens19
    ip: '10.255.255.200/24'
    mtu: 9000


#############
###  ZFS  ###
#############
# NOTE: The pool(s) below should be created and imported.
# Frankly, not worth writing a whole role to do this, since any data on them
# shouldn't go away -- if we're reprovisioning a whole ZFS pool from scratch,
# something else has happened.
zfs_pools:
  - name: tank
    mountpoint: /mnt/tank


#####################
###  dab-storage  ###
#####################
# Bind mount mappings for NFS sharing
bind_mounts:
  - mountpoint: /srv/nfs/vm-backups
    src: /mnt/tank/backups/vm
  - mountpoint: /srv/nfs/media
    src: /mnt/tank/media
    recursive: yes
  - mountpoint: /srv/nfs/docker
    src: /mnt/tank/docker

# NFS shares to be mounted
#nfs_mounts:
#  - mountpoint: /mnt/whatever
#    src: 10.255.255.200:/srv/nfs/whatever
#    opts: rw,sync,hard,intr


######################
###  bertvv.samba  ###
######################
# Make sure the smb.conf template handles {{ ansible_managed }} appropriately at the top.
samba_apple_extensions: yes
samba_guest_account: nobody
samba_load_homes: true  # shares user $HOME automatically
samba_log: /var/log/samba.log
samba_log_level: 1
samba_mitigate_cve_2017_7494: false  # unneeded for samba >4.6.4
samba_global_include: samba-global.conf  # in master templates dir
samba_shares:
  - name: media
    comment: A place for pirates.
    path: /mnt/tank/media
    public: false
    guest_ok: false
    writable: true
  - name: timemachine
    comment: MacOS backups.
    # This may make a literal "%U" directory to serve, vs. extrapolating to the Samba user.
    # Manually correcting the file and restarting the process can fix.  Not sure why.
    path: "/mnt/tank/backups/timemachine/%U"
    include_file: samba-timemachine.conf  # in master templates dir


######################
###  grog.package  ###
###################### 
package_list:
  - name: avahi-daemon
  - name: bash-completion
  - name: curl
  - name: fio
  - name: git
  - name: hddtemp
  - name: htop
  - name: iftop
  - name: iotop
  - name: mc
  - name: ncdu
  - name: net-tools
  - name: nfs-kernel-server
  - name: nmap
  - name: openssh-server
  - name: python
  - name: qemu-guest-agent  # Proxmox/QEMU
  #- name: open-vm-tools     # VMWare
  - name: samba
  #- name: sanoid           # ZFS snapshots
  - name: smartmontools
  - name: ssh-import-id
  - name: tmux
  - name: tree
  - name: wget
  - name: xfsprogs
  - name: zfsutils-linux
  - name: zsh


############################
###  geerlingguy.docker  ###
############################
docker_edition: "ce"
docker_compose_version: "1.28.4"
docker_users: 
  - david


#########################
###  geerlingguy.nfs  ###
#########################
nfs_exports:
  #-"/srv/nfs               10.255.255.0/24(rw,sync,no_subtree_check,crossmnt)"
  - "/srv/nfs/docker        10.255.255.0/24(rw,sync,no_subtree_check)"
  - "/srv/nfs/media         10.255.255.0/24(rw,sync,no_subtree_check)"
  - "/srv/nfs/media/tv      10.255.255.0/24(rw,sync,no_subtree_check)"
  - "srv/nfs/media/movies   10.255.255.0/24(rw,sync,no_subtree_check)"
  - "/srv/nfs/vm-backups    10.255.255.10/32(rw,sync,no_subtree_check,no_root_squash)"

