---
target_os: debian
ansible_user: david
ansible_python_interpreter: /usr/bin/python3

######################
###  grog.package  ###
###################### 
package_list:
  - name: curl
  - name: git
  - name: htop
  - name: net-tools
  - name: python3
  - name: qemu-guest-agent  # Proxmox/QEMU
  - name: ssh-import-id
  - name: tmux
  - name: tree
  - name: wget
  - name: zsh

############################
###  geerlingguy.docker  ###
############################
docker_edition: "ce"
docker_packages_state: latest
docker_install_compose_plugin: true
docker_compose_package: docker-compose-plugin
docker_compose_package_state: latest
docker_users: 
  - david

######################
###  dab-gitrepos  ###
######################
gitrepos:
  - name: docker
    url: https://github.com/economycomfort/docker.git
    path: /home/david/repos/docker
    #uid: 1000
    #gid: 1000
    #overwrite: no
    #become: no