---
target_os: debian
ansible_become: yes
ansible_user: kali  # key only
ansible_python_interpreter: /usr/bin/python3


######################
###  grog.package  ###
###################### 
#package_list:
#  - name: curl
#  - name: git
#  - name: zsh
