---
target_os: debian
ansible_user: david
ansible_python_interpreter: /usr/bin/python3


########################
###  dab-networking  ###
########################
network_interfaces:
  - name: ens18
    dhcp: true
    #ip: '192.168.1.201/24'
    #gateway: '192.168.1.1'
    #dns: '192.168.1.1'
    #domain: brooks.haus
    #mtu: 1500
  - name: ens19
    ip: '10.255.255.202/24'
    mtu: 9000


#####################
###  dab-storage  ###
#####################

## NFS shares to be mounted
nfs_mounts:
  - mountpoint: /mnt/nfs
    src: 10.255.255.200:/srv/nfs


######################
###  dab-gitrepos  ###
######################
gitrepos:
  - name: docker
    url: https://github.com/economycomfort/docker.git
    path: /home/david/git/docker
    #uid: 1000
    #gid: 1000
    #overwrite: no
    #become: no


######################
###  grog.package  ###
###################### 
package_list:
  - name: bash-completion
  - name: curl
  - name: fio
  - name: git
  - name: htop
  - name: iftop
  - name: iotop
  - name: mc
  - name: net-tools
  - name: openssh-server
  - name: python
  - name: qemu-guest-agent  # Proxmox/QEMU
  - name: ssh-import-id
  - name: tmux
  - name: toilet
  - name: tree
  - name: wget
  - name: zsh


############################
###  geerlingguy.docker  ###
############################
docker_edition: "ce"
docker_compose_version: "1.28.4"
docker_users: 
  - david
