---
target_os: debian
ansible_user: david
ansible_python_interpreter: /usr/bin/python3

######################
###  grog.package  ###
###################### 
package_list:
  - name: curl
  - name: git
  - name: htop
  - name: net-tools
  - name: python3
  - name: ssh-import-id
  - name: toilet
  - name: tmux
  - name: tree
  - name: zsh