---
target_os: debian
ansible_user: root  # key only
ansible_python_interpreter: /usr/bin/python3

## This is a hypervisor, keep it as 'clean' as possible

###################
##  dab-proxmox  ##
###################
proxmox_email: d+proxmox@vhf.sh
proxmox_timezone: US/Eastern
proxmox_backup_dirs:  # where pve /etc backups go
  - "/mnt/pve/ext-ssd/pve-config"
  - "/mnt/pve/servo-nfs/pve-config"
proxmox_backup_disk_mount: /mnt/pve/ext-ssd  # Where does backup disk mount?
proxmox_backup_disk_label: INTEL_S3610_400G # Disklabel of backup disk (see /dev/disk/by-label)
proxmox_backup_disk_fstype: ext4  # Backup disk fstype
proxmox_backup_disk_opts: auto,nofail,noatime,rw

######################
###  grog.package  ###
###################### 
package_list:
  - name: curl
  - name: fio
  - name: git
  - name: htop
  - name: iftop
  - name: iotop
  - name: libguestfs-tools
  - name: lm-sensors
  - name: net-tools
  - name: smartmontools
  - name: ssh-import-id
  - name: toilet
  - name: tree
  - name: tmux
  - name: vim
  - name: wget
  - name: zsh

#########################
###  geerlingguy.ntp  ###
#########################
ntp_enabled: yes
ntp_timezone: US/Eastern
ntp_package: chrony     # ntp or chrony
ntp_daemon: chrony
ntp_config_file: /etc/chrony/chrony.conf
ntp_manage_config: yes # allow role to manage NTP config
ntp_servers: 
  - "time.cloudflare.com iburst"
  - "time.google.com iburst"

###############################
###  simoncaron.pve_addons  ###
###############################
pve_addons_enable_dark_theme: no
pve_addons_remove_subscription_nag: yes
pve_addons_disable_enterprise_repo: no
pve_addons_remove_enterprise_repo: yes
pve_addons_add_no_subscription_repo: yes
