---
target_os: debian
ansible_user: root  # key only
ansible_python_interpreter: /usr/bin/python3

## This is a hypervisor, keep it as 'clean' as possible

######################
###  grog.package  ###
###################### 
package_list:
  - name: curl
  - name: fio
  - name: ncdu
  - name: git
  - name: htop
  - name: iftop
  - name: iotop
  - name: libguestfs-tools
  - name: net-tools
  - name: ssh-import-id
  - name: tree
  - name: wget
  - name: zsh

#########################
###  geerlingguy.ntp  ###
#########################
ntp_enabled: true
ntp_timezone: America/New_York
ntp_package: chrony     # ntp or chrony
ntp_daemon: chrony
ntp_config_file: /etc/chrony/chrony.conf
ntp_manage_config: true # allow role to manage NTP config
ntp_servers: 
  - "time.cloudflare.com iburst"
  - "time.google.com iburst"

###############################
###  simoncaron.pve_addons  ###
###############################
pve_addons_enable_dark_theme: false
pve_addons_remove_subscription_nag: true
pve_addons_disable_enterprise_repo: false
pve_addons_remove_enterprise_repo: true
pve_addons_add_no_subscription_repo: true
