---
target_os: debian
ansible_become: no
ansible_user: root  # key only
ansible_python_interpreter: /usr/bin/python3

## This is a hypervisor, keep it as 'clean' as possible

######################
###  grog.package  ###
###################### 
package_list:
  - name: curl
  - name: fio
  - name: git
  - name: htop
  - name: iftop
  - name: iotop
  - name: libguestfs-tools
  - name: net-tools
  - name: openssh-server
  - name: ssh-import-id
  - name: tree
  - name: wget
  - name: zsh

#########################
###  geerlingguy.ntp  ###
#########################
ntp_enabled: true
ntp_timezone: America/New_York
ntp_package: ntp
ntp_config_file: /etc/ntp.conf
ntp_manage_config: true # allow role to manage NTP config
ntp_servers: 
  - "time.cloudflare.com iburst"
