---
target_os: ubuntu
ansible_user: david
ansible_python_interpreter: /usr/bin/python3

#############
###  ZFS  ###
#############
# NOTE: The pool(s) and datasets below should be created and imported prior to 
# playbook execution.
zpools:
  - name: tank
    mountpoint: /mnt/tank
  - name: fast
    mountpoint: /mnt/fast

zdatasets:
  - name: fast/appdata
    mountpoint: /mnt/fast/appdata
  - name: fast/docker
    mountpoint: /var/lib/docker
  - name: fast/downloads
    mountpoint: /mnt/fast/downloads
  - name: fast/home
    mountpoint: /mnt/fast/home
  - name: tank/fast-snapshots
    mountpoint: /mnt/tank/fast-snapshots
  - name: tank/timemachine
    mountpoint: /mnt/tank/timemachine
  - name: tank/proxmox
    mountpoint: /mnt/tank/proxmox
  - name: tank/media
    mountpoint: /mnt/tank/media

zhome: /mnt/fast/home    # dataset for /home

########################
##  Sanoid / Syncoid  ##
########################
syncoid_src_dataset: fast
syncoid_dst_dataset: tank/fast-snapshots
syncoid_exclude_patterns:
  - fast/docker/*

############################
###  geerlingguy.docker  ###
############################
docker_edition: "ce"
docker_packages_state: latest
docker_install_compose_plugin: yes
docker_compose_package: docker-compose-plugin
docker_compose_package_state: latest
docker_users: 
  - david
## Docker uses zfs by default if /var/lib/docker is itself zfs.
#docker_daemon_options:
#  storage-driver: "zfs"
#  data-root: "/mnt/fast/docker"

#########################
###  geerlingguy.nfs  ###
#########################
nfs_exports:
  - "/mnt/tank/media             10.255.255.0/24(rw,sync)"
  - "/mnt/tank/proxmox           10.255.255.10/32(rw,sync,no_root_squash,crossmnt)"

######################
###  grog.package  ###
###################### 
package_list:
  - name: avahi-daemon
  - name: btop
  - name: fio
  - name: git
  - name: git-crypt
  - name: gnupg
  - name: iftop
  - name: iotop
  - name: mc
  - name: ncdu
  - name: net-tools
  - name: nfs-kernel-server
  - name: nmap
  - name: python3
  - name: qemu-guest-agent # Proxmox/QEMU
  - name: rsync
  - name: samba
  - name: sanoid
  - name: smartmontools
  - name: ssh-import-id
  - name: tmux
  - name: toilet
  - name: tree
  - name: whois
  - name: zfsutils-linux
  - name: zsh

#############################
###  vladgh.samba.server  ###
#############################
# Make sure the smb.conf template handles {{ ansible_managed }} appropriately at the top.
samba_apple_extensions: yes
#samba_mitigate_cve_2017_7494: false  # mitigation unneeded and breaks share browsing
samba_guest_account: nobody
samba_load_homes: yes  # shares user $HOME automatically
samba_log: /var/log/samba.log
samba_log_level: 1
samba_log_size: 10000
samba_global_include: servo/samba/samba-global.conf  # in master templates dir
samba_shares:
  - name: media
    comment: A place for pirates.
    path: /mnt/tank/media
    public: no
    guest_ok: no
    writable: yes
  - name: timemachine
    comment: MacOS backups.
    # This may make a literal "%U" directory to serve, vs. extrapolating to the Samba user.
    # Manually correcting the file and restarting the process can fix.  Not sure why.
    path: "/mnt/tank/timemachine/%U"
    include_file: servo/samba/samba-timemachine.conf  # in master templates dir