---
### Networking-related functions

# Sets correct hostname based on host_vars.
- name: ensure correct hostname
  hostname:
    name: "{{ inventory_hostname }}"

# Sets IP address and MTU 9000 on storage network interface.
#   - Modify storage_interface variable in host_vars.
#   - Restarts networking on storage_interface as a handler.
- name: configure storage networking
  ansible.builtin.template:
    src: storage_networking.j2
    dest: "/etc/network/interfaces.d/{{ storage_interface }}"
  notify: restart storage networking (Debian)
  when: ansible_os_family == 'Debian' 


